<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
	<PreserveCompilationContext>true</PreserveCompilationContext>
	<GenerateRuntimeConfigDevFileFlag>true</GenerateRuntimeConfigDevFileFlag>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>	  
	<UseAppHost>true</UseAppHost>
	<PublishWithAspNetCoreHostingModel>true</PublishWithAspNetCoreHostingModel>
	<WebProjectTestHostFramework>net8.0</WebProjectTestHostFramework>
	<UserSecretsId>dotnet-FreteManager.Tests-guid</UserSecretsId>
	<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	  <ShadowCopyAssets>false</ShadowCopyAssets>
	  <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.14" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
	  <ProjectReference Include="..\FreteManager\FreteManager.csproj">
		  <Private>true</Private>
		  <CopyLocalSatelliteAssemblies>true</CopyLocalSatelliteAssemblies>
	  </ProjectReference>
	<WebApplicationTestHost Include="..\FreteManager\Program.cs" />
	<Content Update="xunit.runner.json">
	  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	</Content>
  </ItemGroup>
	
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
